'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
exports.Rusd__factory =
  exports.PriceFeed__factory =
  exports.MultiLot__factory =
    void 0
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MultiLot__factory_1 = require('./MultiLot__factory')
Object.defineProperty(exports, 'MultiLot__factory', {
  enumerable: true,
  get: function () {
    return MultiLot__factory_1.MultiLot__factory
  },
})
var PriceFeed__factory_1 = require('./PriceFeed__factory')
Object.defineProperty(exports, 'PriceFeed__factory', {
  enumerable: true,
  get: function () {
    return PriceFeed__factory_1.PriceFeed__factory
  },
})
var Rusd__factory_1 = require('./Rusd__factory')
Object.defineProperty(exports, 'Rusd__factory', {
  enumerable: true,
  get: function () {
    return Rusd__factory_1.Rusd__factory
  },
})
